name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '7 17 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Setup Python environment
      uses: actions/setup-python@v2
    - name: Fetch latest DIVI data
      uses: mharig/run-python-script-action@v1
      with:
          script: |
            import requests
            import time
            t = time.localtime()
            filename = f'https://www.divi.de/divi-intensivregister-tagesreport-archiv-csv/viewdocument/5549/divi-intensivregister-{t.tm_year}-{t.tm_month}-{t.tm_day}-12-15'
            data = requests.get(filename).text
            with open('DIVI.csv', 'ta') as f:
                f.write(data+'\n')
        
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
